server:
  port: 8080

spring:
  application:
    name: environment-management
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ems
#    username: postgres
#    password: root
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: environment
#            client-secret: tr8AGSU2e81j3NsNlQrcYQfK8ByQTR1A
#            scope: openid,profile,email
#            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/virtusa
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8082/realms/virtusa



#  jpa:
#    hibernate:
#      ddl-auto: update




#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG



  datasource:
    url: jdbc:postgresql://dpg-cvnlphc9c44c73ec1ql0-a.oregon-postgres.render.com:5432/ems_orfe?currentSchema=public
    username: ems_orfe_user
    password: yTGQSPUPFNxvQm9Ja5pCZY9b3DdDpcGD
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true